version: '3'

services:
  tutorial-python:
    container_name: pythontodo
    restart: always
    image: rookout/tutorial-python
    build: .
    environment:
    - ROOKOUT_AGENT_HOST=rookout-agent
    ports:
    - "5000:5000"
    links:
    - rookout-agent
  rookout-agent:
    # The container name must be unique for each tutorial!
    container_name: rookout-agent-pythontut
    image: rookout/agent
    environment:
    - ROOKOUT_TOKEN=$ROOKOUT_TOKEN
    - ROOKOUT_AGENT_TAGS=pytut
    ports:
    - "7486:7486"
